[package]
name = "gsdb"
version = "0.3.25"
description = "A database management tool"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "gsdb_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "mysql",
    "sqlite",
    "chrono",
    "uuid",
    "json",
    "bigdecimal",
] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
tiberius = { version = "0.12", default-features = false, features = [
    "chrono",
    "rustls",
    "bigdecimal",
    "tds73",
] }
tokio-util = { version = "0.7", features = ["compat"] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
bigdecimal = "0.4"
hex = "0.4"
dark-light = "2"
tauri-plugin-store = "2.4.2"
tauri-plugin-keyring = "0.1.0"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
russh = "0.59"
futures = "0.3"
tokio-socks = "0.5"
tauri-plugin-window-state = "2"
tauri-plugin-os = "2"

[target.'cfg(target_os = "macos")'.dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
objc = "0.2"
